version: "3.8"

services:
  database:
    container_name: database
    image: mongo:5.0.15
    restart: always
    ports:
      - 27017:27017
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=asdasd123
      - MONGO_INITDB_DATABASE=crm
    volumes:
      - ./mongoinit.js:/docker-entrypoint-initdb.d/mongoinit.js:ro
      - ./mongo:/data/db